<a href="https://colab.research.google.com/github/sarannetworkprogammer/Data_foundations/blob/main/Numpy_Lab_week9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# QUESTIONS?

# Features

# Machine Learining -> f(x) = y, question: What is x?

# GOAL -> Define a function that takes some x as input and predicts some y

# To learn f(x) automatically from data

# What is x?

# Task Get an A in Data Foundations

# How many hours did they study each week? 3 Numeric (Number)
# Did they take a programming class in the past? Yes or No -> 1 or 0 (binary)
# {A, B, C} -> categorical A [1, 0, 0] , B [0, 1, 0], C [0, 0, 1]
# What if someone majored in A AND B? (multi-hot encoding) -> [1, 1, 0] (categorical)
# What is their GPA (1, 2, 3, or 4) -> Ordinal -> Number 3 -> [1, 0, 0, 0] (number)
# Class Size (small, medium, large) (0-10, 11-50, > 50) -> [0, 0, 1] (cat)


# Ordinal (tall, grande, vente) -> 2 -> [2, 0, 1, 0]

# Categorical (blue, purple, pink) -> [1, 0, 0]
# brown [0, 0, 0]

3, yes, A, 3, large
[3, 1, 1, 0, 0, 3, 0, 0, 1]

# N number of subjects (rows)
# F number of features (columns)


# Example 1: Customer Churn (e.g., predict when a customer will stop being a customer at a bank)

## Features
# Where do they live (categorical)
# Credit score (number)
# How long have they been a customer at this bank? (number)
# Have they referred someone in the past? (binary)

# Example 2: Forecasting (e.g., predict uber usage at a given time in a given city)

## Features
# Is there a big event? Spurs game? Binary
# Population of the city? Number
# How many people used the service last weekend? Number
# how many people used hte serv. last year (same day)? Number


# Example 3: General Prediction: Predict how fast someone will run a 5k race.


## Features

NameError: name 'yes' is not defined

In [1]:
# Numpy

import numpy as np

# Vectors

## Creating

my_array = np.array([1,2,3])

print(my_array)

## Get Size

print(my_array.shape)

## Sum/Average

print(my_array.sum())

print(my_array.mean())

print(my_array.min())

## Addition/Subtraction

coef = np.array([.5, .5])

feats = np.array([10, 20, 5, 75, 18])

#print(feats.dot(coef)) # 10*.5 +  20 * .5



## Fancy indexing

print(feats[feats > 15])


## Dot (inner) product

#print(feats.dot(coef)) # 10*.5 +  20 * .5

feats.argmax()

## Arggggggg (argmax)

# Matricies

matrix = np.array([[1,2,3],[4,5,6]])

print(matrix.shape)

matrix.max(axis=1)

## Similar operations as Vectors




[1 2 3]
(3,)
6
2.0
1
[20 75 18]
(2, 3)


array([3, 6])

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])

coef = np.array([.5, .5, .5])
matrix.dot(coef)

array([3. , 7.5])

# Exercise 1

For this exercise you get to use your imagination. Think of three potential "predictive tasks" (i.e., applications of machine learning). Then, for each task, come up with at least 5 features that are useful for the task. Then, for each feature, think about what type of feature it would be (boolean, Numeric, Ordinal, Categorical, multi-category, etc.) See the example below:

**TASK 1**: Predict customer churn at Facebook (i..e, predicting yes or no if a user will delete their account in the next 6 months)

**Features for Task 1**:
1. How often have they logged into Facebook in the last month?
    1. Numeric, e.g., 7 days
2. How many comments have they made in the last month?
    1. Numeric, e.g., 24 comments
3. How many likes have they given in the last month?
    1. Numeric, e.g., 120 likes
4. How many friends does the user have?
    1. Numeric, e.g., 1 friend
5. What is the longest period of inactivity of the user since creating an account?
    1. Numeric, e.g., 92 days
6. What is the age of the user?
    1. Numeric, e.g., 50 years old
7. Is the user a "verified account"?
    1. boolean, e.g., "yes" or "no"
    
**TIME:** 15 minutes

In [ ]:
# Overall compensation after master degree (> 0)


# Major? categorical
# How many certs? numerical
# How many research papers? numerical
# Final GPA? numerical
# Does degree match job specifications?


# Customer churn Netflix
# which year they started as cust. (numerical)
# Age of user (numerical)
# Sex of user (binary)
# How often user logs in per week (numerical)
# What categorical of content (categorical)
# Screen user time
# Device type

# Exercise 2

You have a dataset containg test grades for each student in a 5th grade class. There were 3 tests in the course. Using the matrix

**YOUR TASK**: The matrix ```grades``` has 3 columns and 20 rows. Using this matrix, complete the following tasks:

1. What is the max test grade for each test? HINT: Use ".max(axis=0)".
2. Which row (user) contains the max test grade for each test? i.e., find the user with the max test grade for each test. HINT: First, select a column, then use ".argmax()".
2. Which user (row) had the highest average grade? HINT: First, calculate use ".mean(axis=1)", then use ".argmax()"
3. Find how many students achived an average score greater than 50. HINT: Calculate average (.mean(axis=1)), then use "fancy indexing" to find scores > 50. 
4. The students performed terribly on each test. Unfortunately, for the students, you (the teacher) are in a bad mood. Instead of curving the students grade up in the class, you want to reduce the students grade by 10\% for not listening to your instruction. HINT: You should use "matrix subtraction" combined with "scalar-matrix" multiplication, i.e., X = A - A*b

**TIME**: 15 minutes

In [4]:
import numpy as np

grades = np.array([[66, 63, 40],
       [65, 32, 28],
       [47, 43, 69],
       [51, 40, 30],
       [39, 32, 60],
       [32, 49, 67],
       [61, 63, 63],
       [45, 39, 29],
       [35, 64, 36],
       [47, 55, 61],
       [34, 21, 40],
       [29, 33, 21],
       [58, 65, 27],
       [44, 57, 40],
       [47, 68, 23],
       [23, 68, 62],
       [22, 33, 31],
       [62, 57, 27],
       [46, 37, 29],
       [35, 62, 25]])

In [5]:
# 1.

print('Ex. 1', grades.argmax(axis=0))

print('Ex. 2 Test 0', grades[:,0].argmax())
print('Ex. 2 Test 1', grades[:,1].argmax())
print('Ex. 2 Test 2', grades[:,2].argmax())

print('Ex. 3', grades.mean(axis=1).argmax())

print('Ex. 4', grades.mean(axis=1)[grades.mean(axis=1) > 50.].shape[0])

print('Ex. 5', grades - grades*.1)

Ex. 1 [ 0 14  2]
Ex. 2 Test 0 0
Ex. 2 Test 1 14
Ex. 2 Test 2 2
Ex. 3 6
Ex. 4 5
Ex. 5 [[59.4 56.7 36. ]
 [58.5 28.8 25.2]
 [42.3 38.7 62.1]
 [45.9 36.  27. ]
 [35.1 28.8 54. ]
 [28.8 44.1 60.3]
 [54.9 56.7 56.7]
 [40.5 35.1 26.1]
 [31.5 57.6 32.4]
 [42.3 49.5 54.9]
 [30.6 18.9 36. ]
 [26.1 29.7 18.9]
 [52.2 58.5 24.3]
 [39.6 51.3 36. ]
 [42.3 61.2 20.7]
 [20.7 61.2 55.8]
 [19.8 29.7 27.9]
 [55.8 51.3 24.3]
 [41.4 33.3 26.1]
 [31.5 55.8 22.5]]


# Exercise 3

Linear regression is fundamental to many areas of data science, including machine learning. Linear regression is defined as
$$ y = \sum_{i=1}^F x_i c_i $$
where $x_i$ is a feature and $c_i$ is a learned coefficient. Intuitively, this is making a prediction for a single instance. We can expand this to many examples in a dataset. This expansion can be rewritten using matricies and vectors as
$$ \mathbf{y} = \mathbf{X} \mathbf{c}$$
where $\mathbf{X}$ is a matrix with $N$ rows and $k$ columns, and $\mathbf{c}$ is a vector with $k$ elements. Building on Exercise 2, the rows of $\mathbf{X}$ represent students and the columns represent tests. We are going to play with the weights of $\mathbf{c}$ to gain intuition of what is happening.

Assume that the 3 tests each student has taken are going to be used to predict what they will get on the final exam. We are going to play with the weights to gain intuition about about linear regression.

**YOUR TASK:** Modify the variable ```weights``` to accomplish the following tasks:
1. Modify the weights such that the final exam score prediction is equal to their last exam (i.e., the last column of ```grades```).
2. Modify the weights such that all students have a score greater than 100.
3. Modify the weights such that all students have a score less than -100.
4. Modify the weights such that all students have predicted grad of 0.

**TIME**: Remainder of class.

In [2]:
weights = np.array([.3333, .3333, .3333]) # MODIFY THE WEIGHTS HERE

In [6]:
predictions = grades.dot(weights) # This is the predictions of the linear regression model.
print(predictions) # This prints the predictions
print(len(predictions))

[56.3277 41.6625 52.9947 40.3293 43.6623 49.3284 62.3271 37.6629 44.9955
 54.3279 31.6635 27.6639 49.995  46.9953 45.9954 50.9949 28.6638 48.6618
 37.3296 40.6626]
20


In [7]:
# Ex 1

weights = np.array([0, 0, 1]) 

predictions = grades.dot(weights) 
print(predictions)

[40 28 69 30 60 67 63 29 36 61 40 21 27 40 23 62 31 27 29 25]


In [8]:
# Ex 2

weights = np.array([10, 10, 10]) 

predictions = grades.dot(weights) 
print(predictions)

[1690 1250 1590 1210 1310 1480 1870 1130 1350 1630  950  830 1500 1410
 1380 1530  860 1460 1120 1220]


In [9]:
# Ex 3

weights = np.array([-10, -10, -10]) 

predictions = grades.dot(weights) 
print(predictions)

[-1690 -1250 -1590 -1210 -1310 -1480 -1870 -1130 -1350 -1630  -950  -830
 -1500 -1410 -1380 -1530  -860 -1460 -1120 -1220]


In [10]:
# Ex 2

weights = np.array([0,0,0]) 

predictions = grades.dot(weights) 
print(predictions)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
