<a href="https://colab.research.google.com/github/sarannetworkprogammer/Data_foundations/blob/main/Saran_Week_8_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python: More Data Annotation and Numpy

Name: 
abc123:
Blank notebook to be used for class exercises.

## Exercise 1

Given the provided numpy array, write code that prints the following:
    
- Print the third row of the array
- Print the second column of the array
- Print the fourth row's third column (this should print a single number).

In [25]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

print(grades)



[[79 95 60]
 [95 60 61]
 [99 67 84]
 [76 76 97]
 [91 84 98]
 [70 69 96]
 [88 65 76]
 [67 73 80]
 [82 89 61]
 [94 67 88]]


In [26]:
# Write Code Here

print(grades[2,:])  # printig 2nd row of the arry

# printing column of the arry 

print(f"second column of the arrary ={grades[:,1]}")


print(f"fourthrow , 3rd column ={grades[3,2]}")


print(grades.dtype)
print(grades.ndim)







[99 67 84]
second column of the arrary =[95 60 67 76 84 69 65 73 89 67]
fourthrow , 3rd column =97
int64
2


In [27]:
# array operations 


a1 = np.array([[1,2,3], [4,5,6]])

print(a1.shape)


a2 = np.array([[1,1,1],[1,1,1]])

print(a2.shape)

print(a1 *a2)

print(a1/a2)

(2, 3)
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]


## Exercise 2

Given the provided array in the Lab file, write code the prints the following:

- The average grade per test (column) (this should print an array with 3 items)
- The average grade per row, i.e., the average test grade per student
- Print the max grade per test
- Print the average across all students (rows) and tests (columns)

In [28]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

In [29]:
# Write Code Here

#print(grades[:,0].mean(), (grades[:,1]).mean(), (grades[:,2]).mean())


print(f"calculating mean of every column = {grades.mean(axis=0)}")

print(f"calculatin mean of every row ={grades.mean(axis=1)}")

print(f"maxgrade per test = {grades.max(axis=0)}")

print(f"Total mean ={grades.mean()}")





calculating mean of every column = [84.1 74.5 80.1]
calculatin mean of every row =[78.         72.         83.33333333 83.         91.         78.33333333
 76.33333333 73.33333333 77.33333333 83.        ]
maxgrade per test = [99 95 98]
Total mean =79.56666666666666


## Exercise 3

Write code that prints the grades of all students that have an average grade less than 90.

In [30]:

import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array



In [31]:
# Write Code Here


avg = grades.mean(axis=1)
print(avg)

bool_index = avg < 90

print(bool_index)

print(grades[bool_index,:])


[78.         72.         83.33333333 83.         91.         78.33333333
 76.33333333 73.33333333 77.33333333 83.        ]
[ True  True  True  True False  True  True  True  True  True]
[[79 95 60]
 [95 60 61]
 [99 67 84]
 [76 76 97]
 [70 69 96]
 [88 65 76]
 [67 73 80]
 [82 89 61]
 [94 67 88]]


## Exercise 4

Write code to adds 10 points every student's test grade **if** their average test grade is greater than 90.

In [32]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array






In [33]:
# Write Code Here

newgrades = grades.copy()

index_bool = grades.mean(axis=1) > 90


print(index_bool)

newgrades[index_bool] += 10

newgrades

[False False False False  True False False False False False]


array([[ 79,  95,  60],
       [ 95,  60,  61],
       [ 99,  67,  84],
       [ 76,  76,  97],
       [101,  94, 108],
       [ 70,  69,  96],
       [ 88,  65,  76],
       [ 67,  73,  80],
       [ 82,  89,  61],
       [ 94,  67,  88]])

## Exercise 5

Write a function that takes two 1-dimensional arrays as input and returns the euclidean distance between the two arrays.

Euclidean distance is defined as

$EDist = \sqrt{(x_0 - v_0)^2 + (x_1 - v_1)^2 + \dots + (x_{D-1} - v_{D-1})^2}$

The square root of a number in numpy can be calculated as np.sqrt(x), where x is a number or array.

Try to complete this exercise with for loops and with vector notation.

In [34]:
# Write Code Here METHOD 1  Traditional method with list method 2 descirbed in below block

def cal(X,V):
  
  sum = 0

  for x,v in zip(X,V):
    sum = sum + (x-v)**2
  
  result = sum **0.5
  return result


X = [1,1,1]
V = [2,2,2]

result = cal(X,V)

print(f"result ={result}")

result =1.7320508075688772


In [35]:
# METHOD 2 
import numpy as np
def edist1(X,V):

  return np.sqrt(((X-V)**2).sum())

X = np.array([1,2,3,4])
V = np.array ([5,6,7,8])

result = edist1(X,V)

print(result)







8.0


## Exercise 6

Write code to load the data in the "iris.csv" into numpy arrays.

The frst 4 columns are the features/attributes. The last column is the
class. Simply load the class as a list of strings. Don't forget to convert the
dataset into a numpy array. You can use either DictVectorizer or the CSV
method on the previous slide to load the features.

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [37]:
with open("/content/drive/MyDrive/Colab Notebooks/iris.csv") as in_file:
    count = 0
    for row in in_file:
      print(row.strip())
      count += 1
      if count == 10:
          break

5.1,3.5,1.4,0.2,Iris-setosa
4.9,3.0,1.4,0.2,Iris-setosa
4.7,3.2,1.3,0.2,Iris-setosa
4.6,3.1,1.5,0.2,Iris-setosa
5.0,3.6,1.4,0.2,Iris-setosa
5.4,3.9,1.7,0.4,Iris-setosa
4.6,3.4,1.4,0.3,Iris-setosa
5.0,3.4,1.5,0.2,Iris-setosa
4.4,2.9,1.4,0.2,Iris-setosa
4.9,3.1,1.5,0.1,Iris-setosa


In [38]:
import numpy as np
import csv

X = []
Y= []
with open("/content/drive/MyDrive/Colab Notebooks/iris.csv") as in_file:
  iCSV = csv.reader(in_file, delimiter=",")

  for row in iCSV:
    X.append([float(x) for x in row[:-1]])
    Y.append(row[-1])

X = np.array(X)
Y = np.array(Y)

print(X.shape)
print(Y.shape)

(150, 4)
(150,)


In [39]:
from sklearn.feature_extraction import DictVectorizer


X_list_dict =[]

Y= []
with open("/content/drive/MyDrive/Colab Notebooks/iris.csv") as in_file:
  iCSV = csv.reader(in_file, delimiter=",")

  for row in iCSV:

    features = {"col_1":float(row[0]),
                "col_2":float(row[0]),
                "col_3":float(row[0]),
                "col_4":float(row[0]),
                }
    X_list_dict.append(features)
    Y.append(row[-1])

vec = DictVectorizer(sparse=False)

X = vec.fit_transform(X_list_dict)

  
Y = np.array(Y)

print(X.shape)
print(Y.shape)


(150, 4)
(150,)


In [40]:
# Write code here