<a href="https://colab.research.google.com/github/sarannetworkprogammer/Data_foundations/blob/main/week8_practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Reshaping and transposing
"""
np.arange(6).reshape(2,3)
order columns


np.arange(6).reshape(2,3).T

Fast element wise functions

abs, fasb
sqrt

np.sqrt

np.square


np.abs

np.exp

np.sign

np

we are converting tabular data to matrices for mathematical computation like csv files to tabular data ------> Matrices


"""

In [1]:
import numpy as np

grades = [[79, 95, 60],
          [95, 60, 61],
          [99, 67, 84],
          [76, 76, 97],
          [91, 84, 98],
          [70, 69, 96],
          [88, 65, 76],
          [67, 73, 80],
          [82, 89, 61],
          [94, 67, 88]] # "grades" is a list of lists.

grades = np.array(grades) # Converts "grades" into a numpy array

grades.T


array([[79, 95, 99, 76, 91, 70, 88, 67, 82, 94],
       [95, 60, 67, 76, 84, 69, 65, 73, 89, 67],
       [60, 61, 84, 97, 98, 96, 76, 80, 61, 88]])

In [3]:
np.exp(grades)   # e^79


print(np.sqrt(grades))

[[8.88819442 9.74679434 7.74596669]
 [9.74679434 7.74596669 7.81024968]
 [9.94987437 8.18535277 9.16515139]
 [8.71779789 8.71779789 9.8488578 ]
 [9.53939201 9.16515139 9.89949494]
 [8.36660027 8.30662386 9.79795897]
 [9.38083152 8.06225775 8.71779789]
 [8.18535277 8.54400375 8.94427191]
 [9.05538514 9.43398113 7.81024968]
 [9.69535971 8.18535277 9.38083152]]


In [5]:
np.ceil(np.sqrt(grades))

array([[ 9., 10.,  8.],
       [10.,  8.,  8.],
       [10.,  9., 10.],
       [ 9.,  9., 10.],
       [10., 10., 10.],
       [ 9.,  9., 10.],
       [10.,  9.,  9.],
       [ 9.,  9.,  9.],
       [10., 10.,  8.],
       [10.,  9., 10.]])

In [9]:
# matrix multiplication  no of columns = no of rows
# row, vector ,column vector, Diagonla matrix, vector product ----scalar logistic regression 

a = b = np.arange(5)
a
print(a.dot(b))  # dot prduct 










30


In [13]:
a = np.array([[1,0,1],[0,1,0]])

b = np.random.randint(0,5,(3,2))

print(a)
print(b)


a.dot(b)

[[1 0 1]
 [0 1 0]]
[[0 3]
 [3 4]
 [2 2]]


array([[2, 5],
       [3, 4]])

In [16]:
# scaling diagonal matrix by making daigonal matrix 
import numpy as np
scaling = [1.1, 1.05, 1.03]
"""
latency of numpy optmized algorimthms
arg, arg max 

which gives indices of the min max

a.sort()


"""


Every thing is avector


Data objects , Attribute types

Customers
Students,professors, Courses
Tweets
Images
Genes, Drugs, Procedures
Attribute


Data object represents entity 

Attribute is data field (synonyms dimensions, /features/variables 

Types of attributes

Nominal : one feature hair color, reg green , cycling one category

Binary : yes or no 

ordinal : drink_size, which coffe is sell the most , professional rank short tall or samll or medium or large

Grade (A, B, C , ) Professional rank (assistant, tenure, associate , Full professor)

Numerical : Things (70F )
Speed


Goal data object transform to a vector , nominal 

eg hair_color (black = 0 , blonde =1, red =2)

no inherent order of categoires


One hot encoding

hair_color 

black = [1,0,0]
blonde = [0,1,0]
red = [0,0,1]

when there is two unique classes we will go to binary


sklearn sckit 

dict vecotrizes -----numpy array  using one hot encoding

data set for the people












In [18]:
import numpy as np

vec = np.zeros((3))
print(vec)

[0. 0. 0.]


In [25]:
from sklearn.feature_extraction import DictVectorizer

datasetDicts =[{"age":1,"hair_color":"blue"},
               {"age":2,"hair_color":"green"},
               {"age":5,"hair_color":"red"}]
 
vec = DictVectorizer(sparse=False)   # take list of dicts and converts matrices

dataset = vec.fit_transform(datasetDicts)

print(dataset)

print(vec.feature_names_)


new_data = [{"age":1,"hair_color":"purple"},]

new_x = vec.transform(new_data)

[[1. 1. 0. 0.]
 [2. 0. 1. 0.]
 [5. 0. 0. 1.]]
['age', 'hair_color=blue', 'hair_color=green', 'hair_color=red']


what if someone has multiple hair colors

multi hot encoding


multi label binarizer

 np.hstack horizonal stack merge them add it no of colours

In [ ]:
vec = np.zeros(3)